version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: contained-postgres
    env_file: 
      - .env
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data:
